### ISSUE TITLE
Deploy docs to GitHub Pages failing

### ISSUE THREAD

**Issue by docNord** [Ingenjorsarbete-For-Klimatet/ifk-python-template#16]
Thus, should we build docs for the template or remove the badge? Doesn't really make sense to have the badge unless we plan to build docs, but to me, the readme is plenty.

**Comment by mgcth** [comment]
We could build it for the template explaining the template, but I think it that is overkill. I think it makes sense to have it as is, too. I want the template to be as featured as possible, so I don't have to recreate the same stuff later, including badges.

**Comment by docNord** [comment]
I agree with the sentiment, however it bugs me to have a "failing" badge in our template repo

**Comment by mgcth** [comment]
Agree, we don't need that badge there, as that README will be replaced with the templated one anyway. However, I think we should find a way to use one README file first.
